version: 2.1

orbs:
  python: circleci/python@4.0.0

jobs:
  build-and-test:
    executor:
      name: python/default
      tag: '3.12'
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: poetry run pytest

workflows:
  main:
    jobs:
      - build-and-test
