"""Create points table

Revision ID: 23d20a30b2b5
Revises:
Create Date: 2025-11-26 19:08:13.345206

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "23d20a30b2b5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
