"""Adding autoincrement to point id

Revision ID: 7a94dabbca0d
Revises: 91218b438dc4
Create Date: 2025-12-09 17:58:14.596868

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "7a94dabbca0d"
down_revision: Union[str, Sequence[str], None] = "91218b438dc4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE points
        ALTER COLUMN id
        DROP DEFAULT;

        ALTER TABLE points
        ALTER COLUMN id
        ADD GENERATED BY DEFAULT AS IDENTITY;
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE points
        ALTER COLUMN id
        DROP IDENTITY IF EXISTS;
    """)

    # ### end Alembic commands ###
